package net.fornwall.jelf;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

public class ElfNoteSection extends ElfSection {

    /**
     * A possible value of the {@link #n_type} where the description should contain {@link GnuAbiDescriptor}.
     * <p>
     * Note types are specific to the note owner, so this value only has this meaning in a note with the
     * "GNU" name - it is for example NT_PRSTATUS in a note owned by "CORE".
     */
    public static final int NT_GNU_ABI_TAG = 1;
    /**
     * A possible value of the {@link #n_type} for a note containing synthetic hwcap information.
     * <p>
     * The descriptor begins with two words:
     * word 0: number of entries
     * word 1: bitmask of enabled entries
     * Then follow variable-length entries, one byte followed by a '\0'-terminated hwcap name string.  The byte gives the bit
     * number to test if enabled, <code>(1U &lt;&lt; bit) &amp; bitmask</code>.
     */
    public static final int NT_GNU_HWCAP = 2;
    /**
     * A possible value of the {@link #n_type} for a note containing build ID bits as generated by "ld --build-id".
     * <p>
     * The descriptor consists of any nonzero number of bytes.
     */
    public static final int NT_GNU_BUILD_ID = 3;

    /**
     * A possible value of the {@link #n_type} for a note containing a version string generated by GNU gold.
     */
    public static final int NT_GNU_GOLD_VERSION = 4;

    /**
     * The descriptor content of a link {@link #NT_GNU_ABI_TAG} type note.
     * <p>
     * Accessible in {@link #descriptorAsGnuAbi()}.
     */
    public static final class GnuAbiDescriptor {

        /**
         * A possible value of {@link #operatingSystem}.
         */
        public static final int ELF_NOTE_OS_LINUX = 0;
        /**
         * A possible value of {@link #operatingSystem}.
         */
        public static final int ELF_NOTE_OS_GNU = 1;
        /**
         * A possible value of {@link #operatingSystem}.
         */
        public static final int ELF_NOTE_OS_SOLARIS2 = 2;
        /**
         * A possible value of {@link #operatingSystem}.
         */
        public static final int ELF_NOTE_OS_FREEBSD = 3;
        /**
         * A possible value of {@link #operatingSystem}.
         */
        public static final int ELF_NOTE_OS_KNETBSD = 4;

        /**
         * One of the ELF_NOTE_OS_* constants in this class.
         */
        public final int operatingSystem;
        /**
         * Major version of the required ABI.
         */
        public final int majorVersion;
        /**
         * Minor version of the required ABI.
         */
        public final int minorVersion;
        /**
         * Subminor version of the required ABI.
         */
        public final int subminorVersion;

        public GnuAbiDescriptor(int operatingSystem, int majorVersion, int minorVersion, int subminorVersion) {
            this.operatingSystem = operatingSystem;
            this.majorVersion = majorVersion;
            this.minorVersion = minorVersion;
            this.subminorVersion = subminorVersion;
        }

        @Override
        public boolean equals(Object o) {
            if (o == null || getClass() != o.getClass()) {
                return false;
            }

            GnuAbiDescriptor that = (GnuAbiDescriptor) o;
            return operatingSystem == that.operatingSystem
                    && majorVersion == that.majorVersion
                    && minorVersion == that.minorVersion
                    && subminorVersion == that.subminorVersion;
        }

        @Override
        public int hashCode() {
            return Objects.hash(operatingSystem, majorVersion, minorVersion, subminorVersion);
        }
    }

    public static final class ElfNote {
        public final String name;

        public final int namesz;

        public final int type;

        private final byte[] descriptorBytes;

        public final byte ei_data;

        ElfNote(String name, int namesz, int type, byte[] descriptorBytes, byte ei_data) {
            this.name = name;
            this.namesz = namesz;
            this.type = type;
            this.descriptorBytes = descriptorBytes;
            this.ei_data = ei_data;
        }

        public byte[] descriptorBytes() {
            return descriptorBytes.clone();
        }

        public String descriptorAsString() {
            return new String(descriptorBytes);
        }

        /**
         * The descriptor of this note interpreted as a {@link GnuAbiDescriptor}, or null if this is not a
         * {@link #NT_GNU_ABI_TAG} note of the "GNU" owner, or if its descriptor is too small to contain one.
         */
        public GnuAbiDescriptor descriptorAsGnuAbi() {
            return gnuAbiDescriptorFrom(name, type, descriptorBytes, ei_data);
        }

        @Override
        public boolean equals(Object o) {
            if (o == null || getClass() != o.getClass()) {
                return false;
            }

            ElfNote note = (ElfNote) o;
            return type == note.type
                    && ei_data == note.ei_data
                    && Objects.equals(name, note.name)
                    && Objects.deepEquals(descriptorBytes, note.descriptorBytes);
        }

        @Override
        public int hashCode() {
            return Objects.hash(name, type, Arrays.hashCode(descriptorBytes), ei_data);
        }
    }

    static final int NHDR_SIZE = 3 * Integer.BYTES;

    /**
     * The size of the descriptor of a {@link #NT_GNU_ABI_TAG} note, which consists of four words.
     */
    static final int GNU_ABI_DESCRIPTOR_SIZE = 4 * Integer.BYTES;

    /**
     * The descriptor of the specified note interpreted as a {@link #NT_GNU_ABI_TAG} one, or null if the
     * note is not a GNU ABI tag note or if its descriptor is too small to contain one.
     */
    private static GnuAbiDescriptor gnuAbiDescriptorFrom(String name, int type, byte[] descriptorBytes, byte ei_data) {
        if (type != NT_GNU_ABI_TAG
                || !ElfNoteTypes.ELF_NOTE_GNU.equals(name)
                || descriptorBytes.length < GNU_ABI_DESCRIPTOR_SIZE) {
            return null;
        }

        ByteBuffer buffer = ByteBuffer.wrap(descriptorBytes)
                .order(ei_data == ElfFile.DATA_LSB ? ByteOrder.LITTLE_ENDIAN : ByteOrder.BIG_ENDIAN);
        return new GnuAbiDescriptor(buffer.getInt(0), buffer.getInt(4), buffer.getInt(8), buffer.getInt(12));
    }

    public final /* uint32_t */ int n_namesz;
    public final /* uint32_t */ int n_descsz;
    public final /* uint32_t */ int n_type;
    private final String n_name;
    private final byte[] descriptorBytes;
    private final GnuAbiDescriptor gnuAbiDescriptor;

    ElfNoteSection(ElfParser parser, ElfSectionHeader header) throws ElfException {
        super(parser, header);

        parser.seek(header.sh_offset);
        n_namesz = parser.readInt();
        n_descsz = parser.readInt();
        n_type = parser.readInt();
        long pos = NHDR_SIZE;

        if (n_namesz < 0 || pos + n_namesz > header.sh_size) {
            throw new ElfException("Invalid note namesz: " + Integer.toUnsignedString(n_namesz));
        }

        byte[] nameBytes = new byte[n_namesz];
        int bytesRead = parser.read(nameBytes);

        if (bytesRead != n_namesz) {
            throw new ElfException("Error reading note name (read=" + bytesRead + ", expected=" + n_namesz + ")");
        }

        long namePos = header.sh_offset + NHDR_SIZE;
        long align = header.sh_addralign;
        long alignedNameEnd = align == Long.BYTES ? noteAlign8(namePos + n_namesz) : noteAlign4(namePos + n_namesz);
        parser.skip((int) (alignedNameEnd - namePos - n_namesz));
        pos = alignedNameEnd - header.sh_offset;

        if (n_descsz < 0 || pos + n_descsz > header.sh_size) {
            throw new ElfException("Invalid note descsz: " + Integer.toUnsignedString(n_descsz));
        }

        descriptorBytes = new byte[n_descsz];
        bytesRead = parser.read(descriptorBytes);

        if (bytesRead != n_descsz) {
            throw new ElfException("Error reading note descriptor (read=" + bytesRead + ", expected=" + n_descsz + ")");
        }

        int nameLen = 0;

        while (nameLen < n_namesz && nameBytes[nameLen] != 0) {
            nameLen++;
        }

        n_name = new String(nameBytes, 0, nameLen);
        gnuAbiDescriptor = gnuAbiDescriptorFrom(n_name, n_type, descriptorBytes, parser.elfFile.ei_data);
    }

    public String getName() {
        return n_name;
    }

    public byte[] descriptorBytes() {
        return descriptorBytes;
    }

    public String descriptorAsString() {
        return new String(descriptorBytes);
    }

    /**
     * The descriptor of the first note of this section interpreted as a {@link GnuAbiDescriptor}, or null if
     * that is not a {@link #NT_GNU_ABI_TAG} note of the "GNU" owner, or if its descriptor is too small.
     */
    public GnuAbiDescriptor descriptorAsGnuAbi() {
        return gnuAbiDescriptor;
    }

    static long noteAlign4(long n) {
        return (n + 3) & -4L;
    }

    static long noteAlign8(long n) {
        return (n + 7) & -8L;
    }

    public List<ElfNote> notes() {
        return readNotes(parser, header.sh_offset, header.sh_size, header.sh_addralign);
    }

    static List<ElfNote> readNotes(ElfParser parser, long offset, long size, long align) {
        parser.seek(offset);
        long pos = offset;
        long end = offset + size;
        List<ElfNote> result = new ArrayList<>();

        while (pos + NHDR_SIZE <= end) {
            int namesz = parser.readInt();
            int descsz = parser.readInt();
            int type = parser.readInt();
            pos += NHDR_SIZE;

            if (namesz < 0) {
                throw new ElfException("Invalid note namesz: " + Integer.toUnsignedString(namesz));
            }

            if (descsz < 0) {
                throw new ElfException("Invalid note descsz: " + Integer.toUnsignedString(descsz));
            }

            long nameEnd = align == Long.BYTES ? noteAlign8(pos + namesz) : noteAlign4(pos + namesz);
            long descEnd = align == Long.BYTES ? noteAlign8(nameEnd + descsz) : noteAlign4(nameEnd + descsz);

            if (nameEnd < pos || descEnd < nameEnd || descEnd > end) {
                throw new ElfException("Note out of bounds (pos=" + pos + ", nameEnd=" + nameEnd + ", descEnd="
                        + descEnd + ", end=" + end + ")");
            }

            byte[] nameBytes = new byte[namesz];
            int bytesRead = parser.read(nameBytes);

            if (bytesRead != namesz) {
                throw new ElfException("Error reading note name (read=" + bytesRead + ", expected=" + namesz + ")");
            }

            if (nameEnd > pos + namesz) {
                parser.skip((int) (nameEnd - pos - namesz));
            }

            pos = nameEnd;

            byte[] desc = new byte[descsz];
            bytesRead = parser.read(desc);

            if (bytesRead != descsz) {
                throw new ElfException(
                        "Error reading note descriptor (read=" + bytesRead + ", expected=" + descsz + ")");
            }

            if (descEnd > pos + descsz) {
                parser.skip((int) (descEnd - pos - descsz));
            }

            pos = descEnd;
            int nameLen = 0;

            while (nameLen < namesz && nameBytes[nameLen] != 0) {
                nameLen++;
            }

            String name = new String(nameBytes, 0, nameLen);
            result.add(new ElfNote(name, namesz, type, desc, parser.elfFile.ei_data));
        }

        return result;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        ElfNoteSection that = (ElfNoteSection) o;
        return n_namesz == that.n_namesz
                && n_descsz == that.n_descsz
                && n_type == that.n_type
                && Objects.equals(n_name, that.n_name)
                && Objects.deepEquals(descriptorBytes, that.descriptorBytes)
                && Objects.equals(gnuAbiDescriptor, that.gnuAbiDescriptor);
    }

    @Override
    public int hashCode() {
        return Objects.hash(n_namesz, n_descsz, n_type, n_name, Arrays.hashCode(descriptorBytes), gnuAbiDescriptor);
    }
}
